apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-react-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-react
  template:
    metadata:
      labels:
        app: node-react
    spec:
      containers:
        - name: node
          image: aahil13/node:latest
          ports:
            - containerPort: 4000
        - name: react
          image: aahil13/react:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node-react-service
spec:
  type: LoadBalancer
  selector:
    app: node-react
  ports:
    - name: node-port
      protocol: TCP
      port: 4000
      targetPort: 4000
    - name: react-port
      protocol: TCP
      port: 3000
      targetPort: 3000
